### PR TITLE
Award updates

### PR DESCRIPTION
**Pull request by frederickobrien**
Replace platinum ribbon with a sticker/badge, make the others text (though I thought we'd already done that?)

### CODE REVIEW

**Comment by frederickobrien** [comment]
This works fine locally but fails on deploy - I suppose because the brand repo assets are split at the moment, @andrewbridge? The gold, silver, and bronze ribbons with writing on them are supposed to stay, with the platinum ribbon replaced by sticker. That's all this change really is. (Plus the platinum awards now link to the 27+ Club tag listing.)

**Comment by andrewbridge** [comment]
Yeah, just standard branding link up needed.

**Review by andrewbridge — APPROVED** [review]

**Comment by andrewbridge** [comment]
All looks fine and works for me, I've approved so you should be able to merge when you're ready.

**Comment by frederickobrien** [comment]
Nice one, thank you.

**Pull request merged**
