### PR TITLE
[Ready for review] Newsletter signup improvements

### PR DESCRIPTION
**Pull request by frederickobrien**
Updating the newsletter signup component so readers can enter their email on-page. Also using this PR as an excuse to look at what - if anything - needs to change for us to be GDPR compliant.

### CODE REVIEW

**Comment by frederickobrien** [comment]
Reckon this is ready for review too. The CSS will probably make your eyes bleed @andrewbridge but it looks neat enough.

**Comment by andrewbridge** [comment]
Code looks fine, but you have the same thoughts as I do about GDPR. Poking around MailChimp, there's a GDPR compliance mode that we almost definitely need to adhere to.

With this mode on, the default signup form generated by MailChimp looks like:

image

While I think the optional name field and format are not required, I think the permissions and legal text are, which might screw us a little in terms of keeping this neat and concise. I'll take a look elsewhere to see what others do for newsletter signup.

**Comment by andrewbridge** [comment]
[This article](https://getanewsletter.com/en/blog/gdpr-friendly-subscription-forms/) seems to suggest we might be okay if we just link to a page discussing newsletter privacy.

**Comment by frederickobrien** [comment]
> 
> 
> [This article](https://getanewsletter.com/en/blog/gdpr-friendly-subscription-forms/) seems to suggest we might be okay if we just link to a page discussing newsletter privacy.
> 
> Edit: With that said, below that article, the site has a box that doesn't link to any legalese...

Ok, I've updated Mailchimp so we have GDPR permissions included (https://eepurl.com/cox6qr). I dare say this is enough for now. If you submit your email in the embedded version it takes you to the full form and asks you to tick off the permission.

To finish the process I'll have to email existing subscribers and ask for them to formally opt in, but that's neither here nor there as far as the PR goes.

**Review by andrewbridge — APPROVED** [review]

**Pull request merged**
